[package]
name = "localization_bank_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
sublime_fuzzy = "0.7.0"
anyhow = "1.0.86"
thiserror = "1.0.61"
